# Generated by Django 3.0.6 on 2020-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200515_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
